<?php

/**
 * Implements hook_help().
 */

function stirrings_user_help($path,$arg) {
  if($path == 'admin/help#stirrings_user') {
    $output = '<h3>' . t('About') . '</h3>';
    $output = '<p>' . t('The Form module show how to Fill up User to Register Form ') . '</p>';
    return $output;
  }
}

/**
 * Implements of hook_menu()
 */

function stirrings_user_menu() {
  $items['stirrings-user-page'] = array(
    'description' => 'This is Simple User Register Form.',
    'page callback' => 'stirrings_user_page_callback',
    'access arguments' => array('stirrings_user_simple_form'),
    'access callback' => TRUE,
  );
  return $items;
}

function stirrings_user_page_callback() {
  return drupal_get_form('stirrings_user_form');
}

/**
 *  A User Register Form
 */

function stirrings_user_form($form, &$form_state) {

     $form['name'] = array(
       '#type' => 'fieldset',
       '#title' => t('Personal Information'),
     );
  $form['name']['first'] = array(
    '#required' => TRUE,
    '#type' => 'textfield',
    '#title' => t('Fisrt Name :'),
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['last'] = array(
    '#type' => 'textfield',
    '#title' => t('Last Name :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['company'] = array(
    '#type' => 'textfield',
    '#title' => t('Company :'),
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['address'] = array(
    '#type' => 'textfield',
    '#title' => t('Address :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['address2'] = array(
    '#type' => 'textfield',
    '#title' => t('Adress2 :'),
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['state'] = array(
    '#type' => 'select',
    '#title' => t('State :'),
    '#required' => TRUE,
    '#default_value' => '',
    '#options' => array(
      'maharashatra' => t('Maharashatra'),
      'pune' => t('Pune'),
      'Delhi' => t('Delhi'),
    ),
  );
  $form['name']['zipcode'] = array(
    '#type' => 'textfield',
    '#title' => t('Zip Code :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );

  $form['name']['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );

  $form['name']['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Address :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );

  $form['usname'] = array(
    '#type' => 'fieldset',
    '#title' => t('Username/Password:'),
  );
  $form['usname']['username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['usname']['password'] = array(
    '#type' => 'password',
    '#title' => t('Password :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['usname']['cpassword'] = array(
    '#type' => 'password',
    '#title' => t('Confirmed Password :'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );

  $form['prefer'] = array(
    '#type' => 'fieldset',
    '#title' => t('Preferences'),
  );

  $form['prefer']['perfermsg'] = array(
    '#type' => 'radios',
    '#title' => t('I would like to receive email communications featuring special offers and updates from Stirrings.com. Stirrings will send no more than two communications per month.'),
    '#options' => array(
      'yes' => t('Yes'),
      'no'=> t('No'),
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Form validation handler for Redister_form()
 * @ see Register Form Submit
 */

function stirrings_user_form_validate($form, &$form_state){
  if(!valid_email_address($form_state['values']['mail'])) {
    form_set_error('mail', t('You must Enter a Valid Email Address .'));
  }
}

/**
 * submit example form.
 */

function stirrings_user_form_submit($form, &$form_state) {
  db_insert('stirrings_user')
    ->fields(array(

      'fname' => $form['name']['first']['#value'],
      'lname' => $form['name']['last']['#value'],
      'company' => $form['name']['company']['#value'],
      'address' => $form['name']['address']['#value'],
      'address2' => $form['name']['address2']['#value'],
      'city' => $form['name']['city']['#value'],
      'state' => $form['name']['state']['#value'],
      'zipcode' => $form['name']['zipcode']['#value'],
      'phone' => $form['name']['phone']['#value'],
      'mail' => $form['name']['mail']['#value'],
      'username' => $form['usname']['username']['#value'],
      'password' => $form['usname']['password']['#value'],
      'cpassword' => $form['usname']['cpassword']['#value'],
      'prefer' => $form['prefer']['perfermsg']['#value'],
    ))
    ->execute();

  drupal_set_message(t('Yes, Your Form Will save'));
}

/**
 * Implements hook_init().
 */

function stirrings_user_init() {
  //Grab the Register Form History from a variable
  $user = variable_get('stirrings_user_history', array());
  //Add current page to Register FOrm
  $user[] = array(
    'title' => strip_tags(drupal_get_title()),
    'path' => $_GET['q'],
    'timestamp' => REQUEST_TIME,
  );

  //Save the Register Form as a variable
  variable_set('stirrings_user_history',$user);
}

/**
 * Implements hook_permission()
 */

function stirrings_user_permission() {
  return array(
    'administer User' => array(
      'title' => t('Administer Register Form Module'),
      'Description' => t('Perform Adminstration task for Register Module'),
    ),

    'access User Form blocks' => array(
      'title' => t('Access Register Form Blocks'),
      'Description' => t('View Blocks Generated by the Register Form Module'),
    ),
  );
}


/**
 * Implements hook_corn()
 */

function stirrings_user_corn() {
  return;
}
